# Generated by Django 5.0.14 on 2026-05-24 09:17

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('Email', 'Email'), ('Telefon', 'Telèfon'), ('WhatsApp', 'WhatsApp'), ('Sistema', 'Sistema')], max_length=20)),
                ('titol', models.CharField(max_length=200)),
                ('destinatari', models.CharField(blank=True, default='', max_length=200)),
                ('data', models.DateField(blank=True, null=True)),
                ('estat', models.CharField(choices=[('enviada', 'Enviada'), ('pendent', 'Pendent'), ('error', 'Error'), ('programada', 'Programada')], default='pendent', max_length=20)),
                ('resum', models.TextField(blank=True, default='')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comunicació',
                'verbose_name_plural': 'Comunicacions',
                'ordering': ['-creat_el'],
            },
        ),
        migrations.CreateModel(
            name='PagamentReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagament', models.DateField()),
                ('import_pagament', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pagament', models.CharField(choices=[('efectiu', 'Efectiu'), ('transferencia', 'Transferència'), ('targeta', 'Targeta'), ('bizum', 'Bizum'), ('altres', 'Altres')], default='transferencia', max_length=20)),
                ('estat', models.CharField(choices=[('pendent', 'Pendent'), ('pagat', 'Pagat'), ('cancelat', 'Cancel·lat')], default='pendent', max_length=20)),
            ],
            options={
                'verbose_name': 'Pagament',
                'verbose_name_plural': 'Pagaments',
                'ordering': ['-data_pagament'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('genere', models.CharField(blank=True, choices=[('Home', 'Home'), ('Dona', 'Dona'), ('Altres', 'Altres')], default='', max_length=10)),
                ('tipus_document', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('NIE', 'NIE'), ('Passaport', 'Passaport')], default='', max_length=15)),
                ('dni_passaport', models.TextField(blank=True, default='')),
                ('dni_passaport_hash', models.CharField(blank=True, default=None, editable=False, max_length=64, null=True, unique=True)),
                ('nacionalitat', models.CharField(blank=True, default='', max_length=80)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('residencia', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefon', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Persones',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='ReservaBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_sortida', models.DateField()),
                ('pagat', models.BooleanField(default=False)),
                ('codi_reserva', models.CharField(blank=True, default='', max_length=30)),
                ('tipus_reserva', models.CharField(blank=True, choices=[('Airbnb', 'Airbnb'), ('Booking', 'Booking'), ('Direct', 'Directa'), ('Altres', 'Altres')], default='', max_length=20)),
                ('estat_reserva', models.CharField(blank=True, choices=[('prereservada', 'Prereservada'), ('reservada', 'Reservada'), ('lista', 'Lista'), ('cancelada', 'Cancelada')], default=None, max_length=20, null=True)),
                ('net', models.BooleanField(default=False)),
                ('limpieza_extra', models.PositiveSmallIntegerField(default=0)),
                ('comentaris_interns', models.TextField(blank=True, default='')),
                ('num_hostes', models.PositiveIntegerField(default=0)),
                ('descompte_immoble_aplicat', models.BooleanField(default=False)),
                ('descompte_immoble_percentatge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descompte_individual_aplicat', models.BooleanField(default=False)),
                ('descompte_individual_percentatge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descompte_individual_motiu', models.TextField(blank=True, default='')),
                ('estat_pagament', models.CharField(choices=[('pendent', 'Pendent'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('retornada', 'Retornada'), ('rebutjada', 'Rebutjada')], default='pendent', max_length=20)),
                ('import_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('import_pagat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('import_pendent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fianca', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metode_pagament', models.CharField(blank=True, default='', max_length=50)),
                ('data_ultim_pagament', models.DateField(blank=True, null=True)),
                ('observacions_pagament', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reserves',
            },
        ),
        migrations.CreateModel(
            name='PerfilPropietari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fiscal', models.CharField(blank=True, default='', max_length=150)),
                ('nif_cif', models.CharField(blank=True, default='', max_length=30)),
                ('adreca_facturacio', models.TextField(blank=True, default='')),
                ('codi_postal_facturacio', models.CharField(blank=True, default='', max_length=12)),
                ('ciutat_facturacio', models.CharField(blank=True, default='', max_length=100)),
                ('provincia_facturacio', models.CharField(blank=True, default='', max_length=100)),
                ('pais_facturacio', models.CharField(blank=True, default='', max_length=100)),
                ('email_facturacio', models.EmailField(blank=True, default='', max_length=254)),
                ('telefon_facturacio', models.CharField(blank=True, default='', max_length=30)),
                ('iban', models.CharField(blank=True, default='', max_length=34)),
                ('observacions_facturacio', models.TextField(blank=True, default='')),
                ('dades_facturacio', core.fields.EncryptedTextField(blank=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_propietari', to='bookings.persona')),
            ],
            options={
                'verbose_name': 'Perfil Propietari',
                'verbose_name_plural': 'Perfils Propietaris',
            },
        ),
        migrations.CreateModel(
            name='PerfilInquili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_inquili', to='bookings.persona')),
            ],
            options={
                'verbose_name': 'Perfil Inquilí',
                'verbose_name_plural': 'Perfils Inquilins',
            },
        ),
        migrations.CreateModel(
            name='Hoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('nom_complet', models.CharField(max_length=150)),
                ('genere', models.CharField(blank=True, choices=[('Home', 'Home'), ('Dona', 'Dona'), ('Altres', 'Altres')], default='', max_length=10)),
                ('relacio_parental', models.CharField(blank=True, default='', max_length=30)),
                ('tipus_document', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('NIE', 'NIE'), ('Passaport', 'Passaport')], default='', max_length=15)),
                ('numero_document', models.CharField(blank=True, default='', max_length=30)),
                ('nacionalitat', models.CharField(blank=True, default='', max_length=80)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('residencia', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefon', models.CharField(blank=True, default='', max_length=30)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostes', to='bookings.persona')),
            ],
            options={
                'verbose_name': 'Hoste',
                'verbose_name_plural': 'Hostes',
                'ordering': ['-es_principal', 'id'],
            },
        ),
    ]
