# Generated by Django 5.0.14 on 2026-05-14 12:30

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiliBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('dni_passaport', core.fields.EncryptedCharField()),
                ('dni_passaport_hash', models.CharField(default='', editable=False, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('dades_facturacio', core.fields.EncryptedTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Inquilí',
                'verbose_name_plural': 'Inquilins',
            },
        ),
        migrations.CreateModel(
            name='ReservaBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_sortida', models.DateField()),
                ('pagat', models.BooleanField(default=False)),
                ('codi_reserva', models.CharField(blank=True, default='', max_length=30)),
                ('tipus_reserva', models.CharField(blank=True, choices=[('Airbnb', 'Airbnb'), ('Booking', 'Booking'), ('Direct', 'Directa'), ('Altres', 'Altres')], default='', max_length=20)),
                ('estat_reserva', models.CharField(blank=True, choices=[('prereservada', 'Prereservada'), ('reservada', 'Reservada'), ('lista', 'Lista'), ('cancelada', 'Cancelada')], default=None, max_length=20, null=True)),
                ('net', models.BooleanField(default=False)),
                ('comentaris_interns', models.TextField(blank=True, default='')),
                ('num_hostes', models.PositiveIntegerField(default=0)),
                ('descompte_immoble_aplicat', models.BooleanField(default=False)),
                ('descompte_immoble_percentatge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descompte_individual_aplicat', models.BooleanField(default=False)),
                ('descompte_individual_percentatge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descompte_individual_motiu', models.TextField(blank=True, default='')),
                ('immoble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='properties.immoble')),
                ('inquili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='bookings.inquilibasic')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reserves',
            },
        ),
        migrations.CreateModel(
            name='PagamentReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagament', models.DateField()),
                ('import_pagament', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pagament', models.CharField(choices=[('efectiu', 'Efectiu'), ('transferencia', 'Transferència'), ('targeta', 'Targeta'), ('bizum', 'Bizum'), ('altres', 'Altres')], default='transferencia', max_length=20)),
                ('estat', models.CharField(choices=[('pendent', 'Pendent'), ('pagat', 'Pagat'), ('cancelat', 'Cancel·lat')], default='pendent', max_length=20)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagaments', to='bookings.reservabasica')),
            ],
            options={
                'verbose_name': 'Pagament',
                'verbose_name_plural': 'Pagaments',
                'ordering': ['-data_pagament'],
            },
        ),
        migrations.CreateModel(
            name='Hoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('nom_complet', models.CharField(max_length=150)),
                ('genere', models.CharField(blank=True, choices=[('Home', 'Home'), ('Dona', 'Dona'), ('Altres', 'Altres')], default='', max_length=10)),
                ('relacio_parental', models.CharField(blank=True, default='', max_length=30)),
                ('tipus_document', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('NIE', 'NIE'), ('Passaport', 'Passaport')], default='', max_length=15)),
                ('numero_document', core.fields.EncryptedCharField(blank=True, default='')),
                ('numero_document_hash', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('nacionalitat', models.CharField(blank=True, default='', max_length=80)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('residencia', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefon', models.CharField(blank=True, default='', max_length=30)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostes', to='bookings.reservabasica')),
            ],
            options={
                'verbose_name': 'Hoste',
                'verbose_name_plural': 'Hostes',
                'ordering': ['-es_principal', 'id'],
            },
        ),
    ]
