# Generated by Django 5.0.14 on 2026-04-21 16:14

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiliBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('dni_passaport', core.fields.EncryptedCharField()),
                ('dni_passaport_hash', models.CharField(default='', editable=False, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('dades_facturacio', core.fields.EncryptedTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Inquilí',
                'verbose_name_plural': 'Inquilins',
            },
        ),
        migrations.CreateModel(
            name='ReservaBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_sortida', models.DateField()),
                ('pagat', models.BooleanField(default=False)),
                ('immoble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='properties.immoble')),
                ('inquili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='bookings.inquilibasic')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reserves',
            },
        ),
    ]
