# Generated by Django 5.0.14 on 2026-04-29 14:08

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservabasica',
            name='codi_reserva',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='comentaris_interns',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='num_hostes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='tipus_reserva',
            field=models.CharField(blank=True, choices=[('Airbnb', 'Airbnb'), ('Booking', 'Booking'), ('Direct', 'Directa'), ('Altres', 'Altres')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Hoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('nom_complet', models.CharField(max_length=150)),
                ('genere', models.CharField(blank=True, choices=[('Home', 'Home'), ('Dona', 'Dona'), ('Altres', 'Altres')], default='', max_length=10)),
                ('relacio_parental', models.CharField(blank=True, default='', max_length=30)),
                ('tipus_document', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('NIE', 'NIE'), ('Passaport', 'Passaport')], default='', max_length=15)),
                ('numero_document', core.fields.EncryptedCharField(blank=True, default='')),
                ('numero_document_hash', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('nacionalitat', models.CharField(blank=True, default='', max_length=80)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('residencia', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefon', models.CharField(blank=True, default='', max_length=30)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostes', to='bookings.reservabasica')),
            ],
            options={
                'verbose_name': 'Hoste',
                'verbose_name_plural': 'Hostes',
                'ordering': ['-es_principal', 'id'],
            },
        ),
    ]
