# Generated by Django 5.0.14 on 2026-05-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservabasica',
            name='limpieza_extra',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
