# Generated by Django 5.0.14 on 2026-05-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_reservabasica_estat_reserva_reservabasica_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservabasica',
            name='codi_cupo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='descompte_immoble_aplicat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='descompte_immoble_percentatge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='percentatge_cupo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
