# Generated by Django 5.0.14 on 2026-05-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_set_descompte_individual_aplicat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagament', models.DateField()),
                ('import_pagament', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pagament', models.CharField(choices=[('efectiu', 'Efectiu'), ('transferencia', 'Transferència'), ('targeta', 'Targeta'), ('bizum', 'Bizum'), ('altres', 'Altres')], default='transferencia', max_length=20)),
                ('estat', models.CharField(choices=[('pendent', 'Pendent'), ('pagat', 'Pagat'), ('cancelat', 'Cancel·lat')], default='pendent', max_length=20)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagaments', to='bookings.reservabasica')),
            ],
            options={
                'verbose_name': 'Pagament',
                'verbose_name_plural': 'Pagaments',
                'ordering': ['-data_pagament'],
            },
        ),
    ]
