# Generated by Django 5.0.14 on 2026-05-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservabasica',
            name='data_ultim_pagament',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='estat_pagament',
            field=models.CharField(choices=[('pendent', 'Pendent'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('retornada', 'Retornada'), ('rebutjada', 'Rebutjada')], default='pendent', max_length=20),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='fianca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='import_pagat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='import_pendent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='import_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='metode_pagament',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='observacions_pagament',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Comunicacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('Email', 'Email'), ('Telefon', 'Telèfon'), ('WhatsApp', 'WhatsApp'), ('Sistema', 'Sistema')], max_length=20)),
                ('titol', models.CharField(max_length=200)),
                ('destinatari', models.CharField(blank=True, default='', max_length=200)),
                ('data', models.DateField(blank=True, null=True)),
                ('estat', models.CharField(choices=[('enviada', 'Enviada'), ('pendent', 'Pendent'), ('error', 'Error'), ('programada', 'Programada')], default='pendent', max_length=20)),
                ('resum', models.TextField(blank=True, default='')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicacions', to='bookings.reservabasica')),
            ],
            options={
                'verbose_name': 'Comunicació',
                'verbose_name_plural': 'Comunicacions',
                'ordering': ['-creat_el'],
            },
        ),
    ]
