# Generated by Django 5.0.14 on 2026-05-16 16:18

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_reservabasica_data_ultim_pagament_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquilibasic',
            options={'ordering': ['nom_complet'], 'verbose_name': 'Inquilí', 'verbose_name_plural': 'Inquilins'},
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='adreca_facturacio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='ciutat_facturacio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='codi_postal_facturacio',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='data_naixement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='email_facturacio',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='genere',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Dona', 'Dona'), ('Altres', 'Altres')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='nacionalitat',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='nif_cif',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='nom_fiscal',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='observacions_facturacio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='pais_facturacio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='provincia_facturacio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='residencia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='telefon_facturacio',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='inquilibasic',
            name='tipus_document',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('NIE', 'NIE'), ('Passaport', 'Passaport')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='inquilibasic',
            name='dni_passaport',
            field=core.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inquilibasic',
            name='dni_passaport_hash',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inquilibasic',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
