# Generated by Django 5.0.14 on 2026-05-21 06:20

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_hoste_numero_document_plain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('genere', models.CharField(blank=True, choices=[('Home', 'Home'), ('Dona', 'Dona'), ('Altres', 'Altres')], default='', max_length=10)),
                ('tipus_document', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('NIE', 'NIE'), ('Passaport', 'Passaport')], default='', max_length=15)),
                ('dni_passaport', models.TextField(blank=True, default='')),
                ('dni_passaport_hash', models.CharField(blank=True, default=None, editable=False, max_length=64, null=True, unique=True)),
                ('nacionalitat', models.CharField(blank=True, default='', max_length=80)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('residencia', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefon', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Persones',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='PerfilPropietari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fiscal', models.CharField(blank=True, default='', max_length=150)),
                ('nif_cif', models.CharField(blank=True, default='', max_length=30)),
                ('adreca_facturacio', models.TextField(blank=True, default='')),
                ('codi_postal_facturacio', models.CharField(blank=True, default='', max_length=12)),
                ('ciutat_facturacio', models.CharField(blank=True, default='', max_length=100)),
                ('provincia_facturacio', models.CharField(blank=True, default='', max_length=100)),
                ('pais_facturacio', models.CharField(blank=True, default='', max_length=100)),
                ('email_facturacio', models.EmailField(blank=True, default='', max_length=254)),
                ('telefon_facturacio', models.CharField(blank=True, default='', max_length=30)),
                ('iban', models.CharField(blank=True, default='', max_length=34)),
                ('observacions_facturacio', models.TextField(blank=True, default='')),
                ('dades_facturacio', core.fields.EncryptedTextField(blank=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_propietari', to='bookings.persona')),
            ],
            options={
                'verbose_name': 'Perfil Propietari',
                'verbose_name_plural': 'Perfils Propietaris',
            },
        ),
        migrations.CreateModel(
            name='PerfilInquili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_inquili', to='bookings.persona')),
            ],
            options={
                'verbose_name': 'Perfil Inquilí',
                'verbose_name_plural': 'Perfils Inquilins',
            },
        ),
        migrations.AddField(
            model_name='hoste',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostes', to='bookings.persona'),
        ),
        migrations.AddField(
            model_name='reservabasica',
            name='inquili_nou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='bookings.persona'),
        ),
    ]
