# Generated by Django 5.0.14 on 2026-05-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_reservabasica_limpieza_extra'),
        ('bookings', '0015_add_comunicacio_email'),
    ]

    operations = [
    ]
