# Generated by Django 5.0.14 on 2026-05-24 09:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('icona', models.CharField(blank=True, default='', max_length=50)),
                ('categoria', models.CharField(choices=[('climatitzacio', 'Climatització'), ('conectivitat', 'Connectivitat'), ('electrodomestics', 'Electrodomèstics'), ('exterior', 'Exterior'), ('altres', 'Altres')], default='altres', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Serveis',
                'ordering': ['categoria', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Immoble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_comercial', models.CharField(max_length=100)),
                ('referencia', models.CharField(blank=True, default='', max_length=50)),
                ('adreca', models.TextField()),
                ('ciutat', models.CharField(blank=True, default='', max_length=100)),
                ('codi_postal', models.CharField(blank=True, default='', max_length=10)),
                ('tipus_immoble', models.CharField(blank=True, default='', max_length=50)),
                ('metres_quadrats', models.PositiveIntegerField(default=0)),
                ('num_habitacions', models.PositiveIntegerField(default=0)),
                ('num_banys', models.PositiveIntegerField(default=0)),
                ('capacitat_maxima', models.PositiveIntegerField(default=0)),
                ('descripcio', models.TextField(blank=True)),
                ('preu_base_nit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descompte_actiu', models.BooleanField(default=False)),
                ('descompte_percentatge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fotos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('hora_checkin_inici', models.TimeField(blank=True, null=True)),
                ('hora_checkin_fi', models.TimeField(blank=True, null=True)),
                ('hora_checkout_inici', models.TimeField(blank=True, null=True)),
                ('hora_checkout_fi', models.TimeField(blank=True, null=True)),
                ('actiu', models.BooleanField(default=True)),
                ('data_registre', models.DateTimeField(auto_now_add=True)),
                ('propietari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immobles', to='bookings.persona')),
                ('serveis', models.ManyToManyField(blank=True, related_name='immobles', to='properties.servei')),
            ],
            options={
                'verbose_name_plural': 'Immobles',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissio', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('nom', models.CharField(max_length=100)),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField()),
                ('preu_nit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_nits', models.PositiveIntegerField(default=1)),
                ('dies_checkin', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('immoble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporades', to='properties.immoble')),
            ],
            options={
                'verbose_name_plural': 'Temporades',
                'ordering': ['data_inici'],
            },
        ),
    ]
