# Generated by Django 5.0.14 on 2026-04-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immoble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_comercial', models.CharField(max_length=100)),
                ('adreca', models.TextField()),
                ('metres_quadrats', models.PositiveIntegerField()),
                ('num_habitacions', models.PositiveIntegerField()),
                ('num_banys', models.PositiveIntegerField()),
                ('capacitat_maxima', models.PositiveIntegerField()),
                ('descripcio', models.TextField(blank=True)),
                ('preu_base_nit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actiu', models.BooleanField(default=True)),
                ('data_registre', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Immobles',
            },
        ),
    ]
