# Generated by Django 5.0.14 on 2026-05-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='comissio',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
    ]
