# Generated by Django 5.0.14 on 2026-05-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_extend_immoble'),
    ]

    operations = [
        migrations.AddField(
            model_name='immoble',
            name='descompte_actiu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='immoble',
            name='descompte_percentatge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
