# Generated by Django 5.0.14 on 2026-05-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_persona_perfilinquili_perfilpropietari'),
        ('properties', '0002_temporada_comissio'),
    ]

    operations = [
        migrations.AddField(
            model_name='immoble',
            name='propietari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immobles', to='bookings.persona'),
        ),
    ]
