# Generated by Django 5.0.14 on 2026-05-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_immoble_propietari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immoble',
            name='propietari_adreca',
        ),
        migrations.RemoveField(
            model_name='immoble',
            name='propietari_dni',
        ),
        migrations.RemoveField(
            model_name='immoble',
            name='propietari_email',
        ),
        migrations.RemoveField(
            model_name='immoble',
            name='propietari_iban',
        ),
        migrations.RemoveField(
            model_name='immoble',
            name='propietari_nom',
        ),
        migrations.RemoveField(
            model_name='immoble',
            name='propietari_telefon',
        ),
    ]
