# Generated by Django 5.0.14 on 2026-05-24 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nip', models.CharField(max_length=20, unique=True, verbose_name="NIP (Número d'Identificació Personal)")),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoImmobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_comercial', models.CharField(max_length=100)),
                ('cif', models.CharField(max_length=20, unique=True)),
                ('adreca', models.TextField()),
                ('email_contacte', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Informació General Immobiliària',
            },
        ),
    ]
