# Generated by Django 5.0.14 on 2026-05-12 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuari_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuari',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usuari',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuari',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuari',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuari',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuari',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='usuari',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
